name: CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['swift:5.1', 'swift:5.2', 'swift:5.3']
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test --parallel --enable-code-coverage
